export const GET_MARKET_QUOTES_LATEST_REQUEST =
  "GET_MARKET_QUOTES_LATEST_REQUEST";
export const GET_MARKET_QUOTES_LATEST_SUCCESS =
  "GET_MARKET_QUOTES_LATEST_SUCCESS";
export const GET_MARKET_QUOTES_LATEST_FAILURE =
  "GET_MARKET_QUOTES_LATEST_FAILURE";

export const GET_LISTING_LATEST_REQUEST = "GET_LISTING_LATEST_REQUEST";
export const GET_LISTING_LATEST_SUCCESS = "GET_LISTING_LATEST_SUCCESS";
export const GET_LISTING_LATEST_FAILURE = "GET_LISTING_LATEST_FAILURE";

export const GET_MAP_REQUEST = "GET_MAP_REQUEST";
export const GET_MAP_SUCCESS = "GET_MAP_SUCCESS";
export const GET_MAP_FAILURE = "GET_MAP_FAILURE";

export const CREATE_NEW_PORTFOLIO = "CREATE_NEW_PORTFOLIO";
