export const GET_MARKET_QUOTES_LATEST_REQUEST =
  "GET_MARKET_QUOTES_LATEST_REQUEST";
export const GET_MARKET_QUOTES_LATEST_SUCCESS =
  "GET_MARKET_QUOTES_LATEST_SUCCESS";
export const GET_MARKET_QUOTES_LATEST_FAILURE =
  "GET_MARKET_QUOTES_LATEST_FAILURE";
